version: "3.8"

services:
  app:
    container_name: online-store
    build:
      context: .
    depends_on:
      - postgres
      - minio
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"

  postgres:
    container_name: events-db
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: events-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"

  nginx:
    container_name: events-nginx
    image: nginx:1.23
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - minio
    ports:
      - "80:80"

volumes:
  postgres_data:
