spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL_LOCALHOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: ${POSTGRES_DRIVER}
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: events_schema
