spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    reset: http://localhost:8080/api/v1/users/passwords/restore?token=
    activate: http://localhost:8080/api/v1/users/activate?token=
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  properties:
    secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDlslslslslVV5IkIxBMzr7OEHXEHd37w
    refresh: 30
    access: 5
    reset: 2
    activating: 3

minio:
  properties:
    url: ${MINIO_URL}
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
    bucketName: ${MINIO_BUCKET_NAME}