spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL_LOCALHOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: ${POSTGRES_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: events_schema
  mail:
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}
    host: ${MAIL.HOST}
    port: ${MAIL.PORT}
    protocol: ${MAIL.PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  properties:
    secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDlslslslslVV5IkIxBMzr7OEHXEHd37w
    refresh: 30
    access: 5
    reset: 2
    activating: 3

email:
  properties:
    reset: http://localhost:8080/api/v1/users/passwords/restore?token=
    activate: http://localhost:8080/api/v1/users/activate?token=
