spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL_LOCALHOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: ${POSTGRES_DRIVER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: events_schema

jwt:
  properties:
    secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDlslslslslVV5IkIxBMzr7OEHXEHd37w
    refresh: 30
    access: 5
