apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: vpetrovaa/events:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EVENTS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: events-configmap
                  key: EVENTS_LOG_LEVEL
            - name: JDBC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: events-configmap
                  key: JDBC_LOG_LEVEL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-configmap
                  key: POSTGRES_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: events-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: events-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: events-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: events-secrets
                  key: MAIL_PORT
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-configmap
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_BUCKET_NAME