apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  MINIO_URL: aHR0cHM6Ly9taW5pbzo5MDAw
  MINIO_ACCESS_KEY: UTNBTTNVUTg2N1NQUVFBNDNQMkY=
  MINIO_SECRET_KEY: enVmK3RmdGVTbHN3UnU3Qko4Nndla2l0bmlmSUxiWmFtMUtZWTNURw==