apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: MINIO_BUCKET_NAME
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: minio-data
              mountPath: /storage
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi